### ISSUE TITLE
Guide looks kinda weird on desktop

### ISSUE THREAD

**Issue by MEEPofFaith** [SimonWoodburyForget/mindustry-modding#13]
![image](https://user-images.githubusercontent.com/54301439/70484305-4c92cc80-1aa0-11ea-8341-b5ee2285dc5d.png)
On desktop, there's a lot of weird empty space to the side, and clicking close to the middle of the screen for the scroll bar feel kinda unnatural.

**Comment by SimonWoodburyForget** [comment]
Fixed the scroll bar position issues. The space on the left side is expected behavior, text is harder to read if it's too wide, so like any website there's a maximum width.
