### ISSUE TITLE
bundles - translate

### ISSUE THREAD

**Issue by Yc7521** [SimonWoodburyForget/mindustry-modding#4]
project
├── bundles
│     ├── bundle.properties
│     ├── <bundles for other languages, like bundle_ru.properties>

`type = item | block | mech | bullet | liquid | status | unit | weather | effect | zone | loadout | typeid`
`mod name = meta.name.toLowerCase().replace(" ", "-")`
`attribute name = name | description`

`type`.`mod name(lowercase and use "-" instead of " ")`-`item name`.`attribute name` = `text`

E.g
```
block.example-mod-silver-wall.name = Серебряная Стена
block.example-mod-silver-wall.description = Стена из серебра.
```

**Comment by SimonWoodburyForget** [comment]
Bundles section added: https://simonwoodburyforget.github.io/mindustry-modding/#Bundles
