### ISSUE TITLE
The website looks pretty bad on mobile

### ISSUE THREAD

**Issue by valtsu41** [SimonWoodburyForget/mindustry-modding#6]
Happens in portrait mode.
![Screenshot_20191204-190435_Chrome](https://user-images.githubusercontent.com/42544217/70163969-0832b580-16c9-11ea-8ce1-0ccbe77ab50b.jpg)

**Comment by SimonWoodburyForget** [comment]
The CSS alignment issue should be fixed. -- I tried to make the page more readable from vertical modes, by adding a minimum width to the contents, and adding a folding button function to the Table of Contents.
