### ISSUE TITLE
Clear a little bit of confusion, I guess

### ISSUE THREAD

**Issue by MEEPofFaith** [SimonWoodburyForget/mindustry-modding#8]
You mention that range is calculated most of the time by 1/10 of a tile. Could on the different range related parameters in the notes say if it's 1/10 or some other measurement.

Also note that weapon range is based off of 1/8 of a tile. Meltdown range is 190, which is 23.75 tiles in-game. 190/23.75 = 8

**Comment by SimonWoodburyForget** [comment]
Well first I'm going to double check. Turret range stat gets defined in `Turret.java`:

```java
stats.add(BlockStat.shootRange, range / tilesize, StatUnit.blocks);
```

Tile size seems to be 8 in `Vars.java`:

```java
/** size of tiles in units */
public static final int tilesize = 8;
```

I'll remove that from FAQ, and add a note to the range section inside turret.

**Comment by MEEPofFaith** [comment]
ok
