### ISSUE TITLE
Confusing note

### ISSUE THREAD

**Issue by MEEPofFaith** [SimonWoodburyForget/mindustry-modding#9]
The note for _homingRange_ is confusing and doesn't make much sense.

_homingRange_: "How far the bullet can home towards target from itself."

**Comment by MEEPofFaith** [comment]
Also, I kinda request notes for what/how _weaveScale_ and _weaveMag_ work

**Comment by SimonWoodburyForget** [comment]
Notes on `weaveScale`/`weaveMag` where added. Changed the notes on `homingRange` to:

> How close the bullet needs from a target in order to home/seek said target.
